core/urls.py
__author__ = 'student'

from django.conf.urls import url, patterns
from views import views, update_views, table_views
from forms import *
import feed

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^landing/', views.index, name='index'),

    # Forms
    url(r'^communication/$', views.communication, name="communication"),
    url(r'^user-profile/', views.userProfile, name='userprofile'),
    url(r'^comms-audit/(?P<audience_id>\d+)/', views.commsAudit, name='commsaudit'),
    url(r'^audience/', views.audience, name="audience"),
    url(r'^sources/', views.sources, name="source"),
    url(r'^tags/', views.tags, name="tags"),
    url(r'^notes/', views.notes, name="notes"),
    url(r'^audit/', views.save_audit, name="save_audit"),
    url(r'^add-to-newsletter/', views.push_to_newsletter, name="push_to_newsletter"),

    # Tables
    url(r'^view-comms/', table_views.view_communcation, name='view_comms'),
    url(r'^view-audience/', table_views.view_audience, name="view_audience"),
    url(r'^view-source/', table_views.view_sources, name="view_sources"),
    url(r'^view-user-profile/', table_views.view_user_profiles, name="view_user_profile"),
    url(r'^view-comms-audit/', table_views.view_comms_audit, name="view_comms_audit"),
    url(r'^view-notes/', table_views.view_notes, name="view_notes"),
    url(r'^view-tags/', table_views.view_tags, name="view_tags"),
    url(r'^view-newsletter/', table_views.view_newsletter_table, name="view_newsletter_table"),
    url(r'^audit-trail/', table_views.audit_trail, name="view_audit_trail"),

    url(r'^comms-feed/', feed.CommunicationFeed()),
    url(r'^newsletter-email/', views.view_newsletter_email, name="newsletter_email"),
    url(r'^newsletter/', views.view_newsletter, name="newsletter"),
    url(r'^export-approved-csv/', views.export_approved_to_csv, name='export_approved_to_csv'),
    url(r'^export-all-csv/', views.export_all_to_csv, name='export_all_to_csv'),
    url(r'^unapproved-articles', views.unapproved_articles, name='unapproved_articles'),
    url(r'^edit/(?P<article_id>\w+)', views.edit_article, name='edit_article'),
    url(r'^delete/(?P<article_id>\w+)', views.delete_article, name='delete_article'),

    # View a single instance of a communication (viewable by public)
    url(r'^external/(?P<comm_id>\w+)/', views.communication_publish, name="communication_publish"),
    url(r'^approve/(?P<article_id>\w+)', views.article_approval, name="article_approval"),

    # Update table data
    url(r'^user-profile/update', update_views.user_profile_update, name="update_user"),
    url(r'^communication/update/', update_views.communication_update, name="update_comm"),

    url(r'^logout', views.logout, name="logout"),
]

stud_comms/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from core.views import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'stud_comms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.login, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comms-system/', include('core.urls')),
    url(r'^accounts/login/', views.login),
)

# Precaution; if debug is left on
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

core/models.py
__author__ = "Jonathan Carlton"
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

# The type of user
USER_TYPE = (
    ('1', 'Staff'),
    ('2', 'Student')
)

# Level in which the communication relates too
LEVEL = (
    ('N/A', 'N/A'),
    ('UG', 'Undergraduate'),
    ('PGT', 'Postgraduate Taught'),
    ('PGR', 'Postgraduate Research'),
    ('ST', 'Staff')
)

class Audience(models.Model):
    """
    Audience model describes the type internal or external
    media format the communication has been published on
    """
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True, null=True)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s %s" % (self.name, self.description)

class Sources(models.Model):
    """
    Describes the source of the data, where/who it has
    come from
    """
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s" % self.name

class UserProfile(models.Model):
    """
    User profile for those that are a member of the site
    """
    user = models.OneToOneField(User)
    username = models.CharField(max_length=255)
    title = models.CharField(max_length=35)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    user_type = models.CharField(max_length=1, choices=USER_TYPE)
    email = models.EmailField()
    smart_card = models.CharField(max_length=255)
    login_count = models.IntegerField()
    last_login = models.DateField(auto_now_add=False, auto_now=True)
    unit = models.CharField(max_length=255)
    known_as = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s" % self.user

class Tags(models.Model):
    """
    Tags relate to the type of Communication that is being stored,
    allows for faster searching on the jQueryTables
    """
    name = models.CharField(max_length=255)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s" % self.name

class Notes(models.Model):
    """
    Notes are defined by the user entering the communication,
    generally small comments in relation to the communication
    """
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=255)
    created_on = models.DateField(null=True, blank=True)
    created_by = models.ForeignKey('UserProfile', blank=True, null=True)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s, %s: %s" % (self.title, self.created_on, self.created_by)

class Communication(models.Model):
    """
    Main bulk of the models, this defines the communication that is
    being added by the users.
    """
    short_desc = models.CharField(max_length=140)
    full_desc = models.CharField(max_length=3000)
    bh_number = models.CharField(max_length=255, null=True, blank=True)
    value_of_award = models.IntegerField(default=0)
    value_awarded_to_ncl = models.IntegerField(default=0, null=True, blank=True)
    project_start_date = models.DateField()
    duration = models.IntegerField(default=0)
    individuals = models.ManyToManyField(UserProfile, related_name="communication_individuals", null=True, blank=True)
    external = models.CharField(max_length=255, blank=True)
    created_by = models.ForeignKey(UserProfile, null=True)
    created_on = models.DateField(null=True)
    source = models.ForeignKey(Sources, null=True)
    admin_checked = models.BooleanField(default=False)
    level = models.CharField(max_length=3, choices=LEVEL)
    tags = models.ManyToManyField(Tags, related_name="communication_tags", null=True, blank=True)
    notes = models.ManyToManyField(Notes, related_name="communication_notes", null=True, blank=True)
    flag = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s" % self.short_desc

class CommsAudit(models.Model):
    """
    Records when the data has been communicated out and by whom
    """
    sent = models.ForeignKey(Communication, null=True)
    sent_by = models.ForeignKey(UserProfile, null=True, blank=True)
    # TODO Should really be a many to many field
    audience = models.ForeignKey(Audience, null=True)
    from_date = models.DateField(null=True)
    to_date = models.DateField(null=True)
    history = HistoricalRecords()

    def __unicode__(self):
        return "%s" % self.sent

class Newsletter(models.Model):
    audit = models.ForeignKey(CommsAudit)
    
    # Twitter will only allow a maximum length of 23, including https://
    # see: https://dev.twitter.com/rest/reference/get/help/configuration
    link = models.CharField(max_length=23)

    def __unicode__(self):
        return "%s" % self.audit.sent.short_desc

core/views/table_views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import csv
from django.utils.encoding import smart_str

__author__ = 'Jonathan Carlton'

from core.forms import *
from core.models import *

@login_required
def view_communcation(request):
    tags = Tags.objects.all()
    notes = Notes.objects.all()
    source = Sources.objects.all()
    queryset = Communication.objects.select_related("individuals", "collaborators").all()

    tag_form = TagForm(request.POST or None)
    if tag_form.is_valid():
        tag_form.save()

    notes_form = NotesForm(request.POST or None)
    if notes_form.is_valid():
        note_instance = notes_form.save(commit=False)
        note_instance.save()

    # CSV file
    if request.method == 'POST':
        ids = request.POST.getlist('select')
        queryset = Communication.objects.filter(id__in=ids)
        response = articles_to_csv(queryset)
        return response

    context = {
        "tag_form": tag_form,
        "notes_form": notes_form,
        "queryset": queryset,
        "tags": tags,
        "notes": notes,
        "source": source
    }

    return render(request, "core/tables/view_comm.html", context)

@login_required
def view_audience(request):
    queryset = Audience.objects.all()
    context = {
        "queryset": queryset,
    }
    return render(request, "core/tables/view_audience.html", context)

@login_required
def view_sources(request):
    queryset = Sources.objects.all()
    context = {
        "queryset": queryset,
    }
    return render(request, "core/tables/view_sources.html", context)

@login_required
def view_user_profiles(request):
    queryset = UserProfile.objects.all()
    context = {
        "queryset": queryset,
    }
    return render(request, "core/tables/view_user_profile.html", context)

@login_required
def view_comms_audit(request):
    queryset = CommsAudit.objects.all()
    audience = Audience.objects.all()
    context = {
        "queryset": queryset,
        "audience": audience
    }
    return render(request, "core/tables/view_comms_audit.html", context)

@login_required
def view_notes(request):
    queryset = Notes.objects.all()
    context = {
        "queryset": queryset,
    }
    return render(request, "core/tables/view_notes.html", context)

@login_required
def view_tags(request):
    queryset = Tags.objects.all()
    context = {
        "queryset": queryset,
    }
    return render(request, "core/tables/view_tags.html", context)

@login_required
def view_newsletter_table(request):
    queryset = Newsletter.objects.all()
    context = {
        "queryset": queryset
    }
    return render(request, "core/tables/view_newsletter.html", context)

@login_required
def audit_trail(request):
    queryset = CommsAudit.history.all()
    context = {
        "queryset": queryset
    }
    return render(request, "core/tables/view_audit_trail.html", context)

def articles_to_csv(queryset):
    """
    Written specfically for the view_comm view
    :param queryset: set of articles
    :return: HttpResponse
    """
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="exported_articles.csv"'

    writer = csv.writer(response)
    writer.writerow([
        smart_str(u'ID'),
        smart_str(u'Short Desc'),
        smart_str(u'Full Desc'),
        smart_str(u'BH Number'),
        smart_str(u'Value'),
        smart_str(u'Value to NCL'),
        smart_str(u'Start Date'),
        smart_str(u'Duration'),
        smart_str(u'Individuals'),
        smart_str(u'External'),
        smart_str(u'Source'),
        smart_str(u'Level'),
    ])

    for i in queryset:
        writer.writerow([
            smart_str(i.pk),
            smart_str(i.short_desc),
            smart_str(i.full_desc),
            smart_str(i.bh_number),
            smart_str(i.value_of_award),
            smart_str(i.value_awarded_to_ncl),
            smart_str(i.project_start_date),
            smart_str(i.duration),
            smart_str(i.individuals.all()),
            smart_str(i.external),
            smart_str(i.source),
            smart_str(i.level)
        ])
    return response

core/views/update_views.py
__author__ = 'Jonathan'

from core.models import UserProfile, Communication
import json, datetime
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

@login_required
@csrf_exempt
def user_profile_update(request):
    if request.method == 'POST':
        pk = request.POST['pk']
        obj = request.POST['name']
        val = request.POST['value']
        d = {obj: val}
        valid_fields = [
            'username', 'title', 'first_name', 'last_name', 'user_type',
            'email', 'smart_card', 'unit', 'known_as', 'role'
        ]
        if obj in valid_fields:
            try:
                UserProfile.objects.filter(pk=pk).update(**d)
                data = {'status': 'success', 'msg': 'updated'}
            except Exception as e:
                data = {'status': 'error', 'msg': 'Value not accepted'}
        else:
            data = {'status': 'error', 'msg': 'field not valid'}
    else:
        data = {'status': 'error', 'msg': 'post not received'}
    return_json = json.dumps(data, default=string_date_json_serializer)
    return HttpResponse(return_json, content_type="application/json")

@login_required
@csrf_exempt
def communication_update(request):
    if request.method == 'POST':
        pk = request.POST['pk']
        obj = request.POST['name']
        val = request.POST['value']
        d = {obj: val}
        valid_fields = [
            'short_desc', 'full_desc', 'bh_number', 'value_of_award', 'value_awarded_to_ncl',
            'project_start_date', 'duration', 'external', 'level', 'admin_checked'
        ]
        if obj in valid_fields:
            try:
                Communication.objects.filter(pk=pk).update(**d)
                data = {'status': 'success', 'msg': 'updated'}
            except Exception as e:
                data = {'status': 'error', 'msg': 'not updated'}
        else:
            data = {'status': 'error', 'msg': 'field not valid'}
    else:
        data = {'status': 'error', 'msg': 'post not received'}
    return_json = json.dumps(data, default=string_date_json_serializer)
    return HttpResponse(return_json, content_type="application/json")

## Date serializer catch for the json converter ##
def string_date_json_serializer(obj):
    temp = None
    if isinstance(obj, datetime.date):
        temp = obj.strftime('%Y/%m%/d')
    return temp

core/templates/core/forms/audience.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}

    <script>
        init.push(function () {
            $("#div_id_description").append('<div id="character-limit-textarea-label" class="limiter-label">Characters left: <span class="limiter-count">255</span></div>');
            $("#id_description").limiter(255, {label:'#character-limit-textarea-label'});
        })
    </script>
{% endblock %}

core/templates/core/forms/comms_audit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="table-primary">
        <div role="grid" id="jq-datatables-wrapper" class="dataTable-wrapper form-inline no-footer">
            {% if is_newsletter %}<form method="POST">{% csrf_token %}{% endif %}
            <table id="jq-datatables" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable no-footer">
                <thead>
                    <th>Sent</th>
                    <th>From Date</th>
                    <th>To Date</th>
                    <th>Audience</th>
                    <th>Sent By</th>
                </thead>
                <tbody>
                    {% for i in data %}
                    <tr>
                        <td>{{ i.sent }}</td>
                        <td>{{ i.from_date }}</td>
                        <td>{{ i.to_date }}</td>
                        <td>{{ i.audience }}</td>
                        <td>{{ i.sent_by }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if is_newsletter %}<button role="button" class="btn btn-primary" type="submit">View Newsletter</button></form>{% endif %}
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#jq-datatables').DataTable();
            $('#jq-datatables-wrapper .table-caption').text("Articles");
        });
    </script>

{% endblock %}

core/templates/core/forms/communication.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Main Article form -->
    {% crispy c_form %}
    <div id="form-errors">{{ form_errors }}</div>
    <!-- / Main Article form -->

    <!-- Tags Modal -->
    <div id="modal-tags" class="modal fade" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times-circle"></i></button>
                    <h4 class="modal-title" id="tag-model-label">Add a new tag</h4>
                </div>
                <div class="modal-body">
                    <form method="POST" action="" id="tag-form">
                        {% csrf_token %}
                        {{ t_form|crispy }}
                        <input type="submit" value="Submit" name="tagmodal" id="tagmodal" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- / Tags Modal -->
    <!-- Notes Modal -->
    <div id="modal-notes" class="modal fade" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hideen="true"><i class="fa fa-times-circle"></i></button>
                    <h4 class="modal-title" id="tag-model-label">Add a new note</h4>
                </div>
                <div class="modal-body">
                    <form method="POST" action="" id="notes-form">
                        {% csrf_token %}
                        {{ n_form|crispy }}
                        <input type="submit" value="Submit" name="notesmodal" id="notesmodal" />
                        <input type="hidden" name="tagmodal" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- / Notes Modal -->

    <script>
        $(document).ready(function () {
            var full_desc = $("#div_id_full_desc");
            var value = $("#div_id_value_of_award");
            var tag = $("#div_id_tags");
            var note = $("#div_id_notes");

            tag.append("<a data-toggle='modal' data-target='#modal-tags'>Add&nbsp;&nbsp;<i class='fa fa-plus'></i></a>");
            tag.append('<br/><a data-toggle="modal" data-target="#modal-notes">Add a note&nbsp;&nbsp;<i class="fa fa-plus"></i></a>');

            full_desc.append('<div id="character-limit-textarea-label" class="limiter-label">Characters left: <span class="limiter-count">3000</span></div>');
            $("#id_full_desc").limiter(3000, {label:'#character-limit-textarea-label'});

            $("#div_id_short_desc").append('<div id="character-limit-input-label" class="limiter-label form-group-margin">Characters left: <span class="limiter-count">140</span></div>');
            $("#id_short_desc").limiter(140, {label:'#character-limit-input-label'});

            full_desc.append('<div class="expanding-input-hidden expanding-input-content"><a data-toggle="modal" data-target="#modal-notes">Add a Note <i class="fa fa-plus"></i></a></div>');
            full_desc.expandingInput({target: 'input[type="text"]', hidden_content: '> div'});

            value.append('<a data-toggle="modal" data-target="#modal-notes">Add a note&nbsp;&nbsp;<i class="fa fa-plus"></i></a>');

            $('#key-btn').on('click', function () { $('a[href="#values"]').tab('show')});
            $('#value-btn').on('click', function () { $('a[href="#involved"]').tab('show')});
            $('#involved-btn').on('click', function () { $('a[href="#additional"]').tab('show')});

            $('#jq-growl-notice').click(function () {
                $.growl.notice({message: "Communication added"});
            });

            $('#tag-form').on('submit', function(e) {
                var data = $('#tag-form').serialize();
                $.ajax({
                    type: 'POST',
                    url: "{% url 'communication' %}",
                    data: data,
                    success: function() {
                        $('#modal-tags').modal('hide');
                        $.growl.notice({
                            message: "Tag Saved: This tag will be added to the new Article"
                        })
                    }
                });
                e.preventDefault();
            });

            $('#notes-form').on('submit', function(e) {
                var data = $('#notes-form').serialize();
                $.ajax({
                    type: 'POST',
                    url: "{% url 'communication' %}",
                    data: data,
                    success: function () {
                        $('#modal-notes').modal('hide');
                        $.growl.notice({
                            message: "Note Saved: This note will be added to the new Article"
                        })
                    }
                });
                e.preventDefault();
            });

            $('#id_tags').select2({
                placeholder: "Select tag",
                allowClear: true
            });

            $('#id_individuals').select2({
                placeholder: "Select involved",
                allowClear: true
            });

        })
    </script>
{% endblock %}

core/templates/core/forms/notes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy n_form %}

    <script>
        init.push(function () {
            $("#div_id_content").append('<div id="character-limit-textarea-label" class="limiter-label">Characters left: <span class="limiter-count">255</span></div>');
            $("#id_content").limiter(255, {label:'#character-limit-textarea-label'});
        })
    </script>
{% endblock %}

core/templates/core/forms/push_newsletter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% crispy form %}

    {% if error_stored %}
        <br />
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong>Already in Newsletter!</strong>
            The communication has already been added to the newsletter
        </div>
    {% endif %}

{% endblock content %}

core/templates/core/forms/sources.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}

    <script>
        init.push(function () {
            $("#div_id_description").append('<div id="character-limit-textarea-label" class="limiter-label">Characters left: <span class="limiter-count">255</span></div>');
            $("#id_description").limiter(255, {label: '#character-limit-textarea-label'});
        })
    </script>
{% endblock %}

core/templates/core/forms/tags.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}

core/templates/core/forms/user_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}